version: '3.8'

services:
  c_dev_container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c_dev_container
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace
      - .zshrc:/root/.zshrc
      - .gitconfig:/root/.gitconfig
      - .git:/root/.git
      - .ssh:/root/.ssh
    working_dir: /workspace
    entrypoint: [ "sh", "-c", "zsh" ]
